version: "3.8"
services:
  admin:
    build: ./Admin
    ports: 
      - 4000:4000
    volumes:
      - ./Apache/uploads:/usr/local/apache2/htdocs/uploads
    networks:
      - vitstudyshare-network

  client:
    build: ./Client
    ports:
      - 3000:3000
    networks:
      - vitstudyshare-network
    environment:
      - APACHE_HOST=apache
      - APACHE_PORT=80

  apache:
    build: ./Apache
    ports: 
      - 8080:80
    volumes:
      - ./Apache/uploads:/usr/local/apache2/htdocs/uploads
    networks:
      - vitstudyshare-network

networks:
  vitstudyshare-network:
    driver: bridge

volumes:
  uploads:
